### ISSUE TITLE
Lack of 'images.txt' and 'region.txt'

### ISSUE THREAD

**Issue by mengyangniu** [foolwood/DaSiamRPN#1]
File "./code/vot.py", line 104, in __init__ 
   self._files = [x.strip('\n') for x in open('images.txt', 'r').readlines()]
File "./code/vot.py", line 106, in __init__ 
   self._region = convert_region(parse_region(open('region.txt', 'r').readline()), region_format)

I didn't find 'images.txt' or 'region.txt'.

Could you please provide these files or the way to generate them? Thanks.

**Comment by HelloRicky123** [comment]
You can try to use this with the VOT toolkit.

**Comment by mengyangniu** [comment]
Btw I can't use VOT toolkit since I don't have a matlab license and I'm not allowed to use pirated software..

**Comment by unaplugin** [comment]
.......................................

**Comment by BagusYusuf** [comment]
hi, if i want to run without vot toolkit, this error is appear, is that possible to run without vot toolkit ??

**Comment by jazzseow** [comment]
@BagusYusuf you can just run vot_SiamRPN.py. just create a text file 'images.txt', which contains paths to test images, something like
"
/home/ctg-sa/jazz_ws/sot/dataset/data/cfnet-validation/tc_Busstation_ce2/0035.jpg
/home/ctg-sa/jazz_ws/sot/dataset/data/cfnet-validation/tc_Busstation_ce2/0036.jpg
/home/ctg-sa/jazz_ws/sot/dataset/data/cfnet-validation/tc_Busstation_ce2/0037.jpg
/home/ctg-sa/jazz_ws/sot/dataset/data/cfnet-validation/tc_Busstation_ce2/0038.jpg
/home/ctg-sa/jazz_ws/sot/dataset/data/cfnet-validation/tc_Busstation_ce2/0039.jpg
/home/ctg-sa/jazz_ws/sot/dataset/data/cfnet-validation/tc_Busstation_ce2/0040.jpg
/home/ctg-sa/jazz_ws/sot/dataset/data/cfnet-validation/tc_Busstation_ce2/0041.jpg
"
and a 'region.txt' , which contain left, top, width, height of the targeted object in the first frame like
"987,394,30,96"

Check the paths, make sure the code is able to find them, and that's it

**Comment by BagusYusuf** [comment]
hi @jazzseow, thanks for your reply, I have re-created the demo.py file and run perfectly
