### ISSUE TITLE
Is this the code of Siamese-RPN, not for DaSiameRPN? or just lack the Incremental learning module?

### ISSUE THREAD

**Issue by kevinjunwei** [foolwood/DaSiamRPN#12]
I cannot find the incremental learning module in the released code. I wonder if this code for DasiameseRPN?

**Comment by zhengzhugithub** [comment]
The code is for our entry of VOT2018, which mainly relies on DaSiameRPN.

**Comment by zhengzhugithub** [comment]
> @zhengzhugithub Hello, do you implement the 'local-to-global strategy' in the code? I didn't find it, could you please tell me?

we  will update it.

**Comment by 297335176** [comment]
Hello, do you implement the ' the incremental learning module ' in the code? I didn't find it, could you please provide me?

**Comment by alexanderfrey** [comment]
When do you plan to update the code ?

**Comment by foolwood** [comment]
@alexanderfrey @297335176 @Kewenjing1020 @kevinjunwei 

We plan to release the code in the near future. I will make an announcement here when it will be available.

Thanks for your question.

**Comment by ybsave** [comment]
Hello, will you release the DaSiamese version of the tracker? Thank you.
