### ISSUE TITLE
the code about RPN

### ISSUE THREAD

**Issue by Cris-zj** [foolwood/DaSiamRPN#14]
Thank you for the great work! Can you give some information about the anchor target layer of RPN part in code? I just try to write the Train part. Thank you for your reply

**Comment by foolwood** [comment]
@Cris-zj 
For the box branch. You can refer to any detection code.

Thanks for your question.

**Comment by Cris-zj** [comment]
@xujiao3628 可以看下DaSiamRPN中3.4章节，鄙人愚见：小目标由于size小，极易丢失，尤其是long-term下，搜索范围小，更难找到目标，扩大搜索，增加找到目标的概率。
