### ISSUE TITLE
How much will the SiamRPN perform worse if the netwok is trained from scratch？

### ISSUE THREAD

**Issue by ZSQflower** [foolwood/DaSiamRPN#16]
Thank you for your excellent work. However, How much will the SiamRPN (or DaSiamRPN) perform worse  if the netwok is trained from scratch (all layers)?

**Comment by foolwood** [comment]
@ZSQflower 

First, all our models are not trained from scratch. We use an Imagenet pretrained model.

Second, train from scratch will get a bad convergence. 

We did not test the performance of this setting.
But I am sure training from scratch will get worse results.

Thanks for your question.
