### ISSUE TITLE
performance on OTB100

### ISSUE THREAD

**Issue by HengLan** [foolwood/DaSiamRPN#17]
The performance of this version on OTB is 0.852 in distance precision, way lower than the results reported in the paper!

**Comment by ucasqcz** [comment]
have you evaluate the model on OTB100 ? is the auc the same with the paper? @HengLan

**Comment by HengLan** [comment]
> have you evaluate the model on OTB100 ? is the auc the same with the paper? @HengLan

Not exactly the same! Not surprised since this is not the original implementation used in the paper.
