### ISSUE TITLE
Will U upload the data argumentation script?

### ISSUE THREAD

**Issue by spark123456789** [foolwood/DaSiamRPN#18]
Hi, after reading your paper, most of your work are mainly focused on the data argumentation part, which affects the performance of the final model. I wonder whether you will upload this part of work.
Thank you for your reply!

**Comment by foolwood** [comment]
@spark123456789 
Sorry for the late reply.
We did not have a plan to release the training code for now. So an isolated data argumentation code is less valuable.
Thanks for your question.
