### ISSUE TITLE
Why no activation function for siamrpn？

### ISSUE THREAD

**Issue by ztf-ucas** [foolwood/DaSiamRPN#20]
Thanks for your remarkable work!
Why no ReLU activation for alexnet conv5 and RPN？
Why no linear activation for regression branch？

**Comment by Jiangfeng-Xiong** [comment]
我想是因为conv5作为是最后一层特征, 两个分支的特征做相关, 如果加了relu的话, 相关出来的都是非负数,但是RPN的目标值存在负数, 所以这里不加ReLU @ztf-ucas

**Comment by zzpustc** [comment]
How much the final loss is? @foolwood

**Comment by foolwood** [comment]
@zzpustc 
Cls Loss is around 0.05
Reg Loss is around 0.15.

**Comment by foolwood** [comment]
@ztf-ucas @zzpustc @Jiangfeng-Xiong 
If you still have a question, you can reopen this issue. But for now, I should close it.
