### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by zkloveai** [foolwood/DaSiamRPN#22]
可以直接输入图片或视频进行检测吗？

**Comment by 361720691** [comment]
大概看了下代码，把视频转成图片序列，作为代码里面images.txt，region.txt替换成初始化窗口就可以了，输出是一个和images同行数的output.txt。

**Comment by zkloveai** [comment]
把视频转成图片序列，这句我明白。
请问“images.txt，region.txt替换成初始化窗口”。中的images.txt 和 region.txt里面是图片信息和锚点框吗？

**Comment by 361720691** [comment]
> 把视频转成图片序列，这句我明白。
> 请问“images.txt，region.txt替换成初始化窗口”。中的images.txt 和 region.txt里面是图片信息和锚点框吗？

images.txt中每一行是一张图片的绝对路径，region.txt只需要一行坐标即可，可以是多个点组成的多边形也可以是矩形框的左上角和右下角。你可以读一读代码，这些信息很容易分析出来的。

**Comment by foolwood** [comment]
@zkloveai @361720691 
Thanks for your question. We write a [demo](https://github.com/foolwood/DaSiamRPN/blob/master/code/demo.py) (less than 40 lines) to test our tracker. You can tailor it to your task.

**Comment by TouchSkyWf** [comment]
In the demo init_rbox = [334.02,128.36,438.19,188.78,396.39,260.83,292.23,200.41]
Why every init_bbox has 8 values. x_min,y_min,width,height are just four values.

**Comment by 361720691** [comment]
> In the demo init_rbox = [334.02,128.36,438.19,188.78,396.39,260.83,292.23,200.41]
> Why every init_bbox has 8 values. x_min,y_min,width,height are just four values.

Four points to locate a box: top left, top right, bottom left, bottom right.
