### ISSUE TITLE
batch_size must be set to 1 ?

### ISSUE THREAD

**Issue by aznikline** [foolwood/DaSiamRPN#26]
# warm up
for i in range(10):
    net.temple(torch.autograd.Variable(torch.FloatTensor(1, 3, 127, 127)).cuda())
    net(torch.autograd.Variable(torch.FloatTensor(1, 3, 255, 255)).cuda())

**Comment by aznikline** [comment]
i set batch_size = 2 and got this:
RuntimeError: invalid argument 2: size '[20 x 256 x 4 x 4]' is invalid for input with 163840 elements at /pytorch/aten/src/TH/THStorage.cpp:84

**Comment by foolwood** [comment]
@aznikline @ZhangSanFengByGit 

Thanks for your question.
We wanted to make our test code as simple as possible. So we did not support a larger batch(>1) in the test code.
