### ISSUE TITLE
不加载预训练权重模型好像不收敛？

### ISSUE THREAD

**Issue by ztf-ucas** [foolwood/DaSiamRPN#27]
@foolwood ！您好，我直接训练，没加载alexnet的预训练权重，然后cls-loss到了0.45就不动了，必须要加载预训练权重吗？您有试过从头训练吗？

**Comment by wxh001qq** [comment]
同问，可以稍微描述一下相关细节么？感觉按论文实现效果不是很好

**Comment by ztf-ucas** [comment]
> 同问，可以稍微描述一下相关细节么？感觉按论文实现效果不是很好

我测试基本没有效果，跟没训练一样。你的模型咋样？

**Comment by wxh001qq** [comment]
> > 同问，可以稍微描述一下相关细节么？感觉按论文实现效果不是很好
> 
> 我测试基本没有效果，跟没训练一样。你的模型咋样？

还是有效果的直接用作者的vot测试代码测

**Comment by hjjlovecyy** [comment]
你们试过out-of-view这种情况了没?发现完全没有效果
或者你们训练完后效果怎样

**Comment by foolwood** [comment]
@ztf-ucas @hjjlovecyy @wxh001qq 

First, all our models are not trained from scratch. We use an Imagenet pretrained model.

Second, train from scratch will get a bad convergence. Even though Kaiming He recently reports that detection can be trained from scratch, the end-to-end deep learning for visual tracking is still challenging. 

We should not negate algorithms just by your own code.

Thanks for your question.
