### ISSUE TITLE
No module named torch

### ISSUE THREAD

**Issue by xjtuwh** [foolwood/DaSiamRPN#30]
你好，我在运行代码的时候在大环境下pip安装了pytorh，但是依然通不过vot套件测试。我用的python是anacoanda中的，但是报错说用的python是/usr/bin中的，不知如何解决这个问题？

报错代码如下：
------------------------------------------------------------------------------------------------------------------------------------------
Initializing workspace ...
Verifying native components ...
Testing TraX protocol support for tracker SiamRPN.
CLIENT: _Creating process /usr/bin/python_  -c "import sys; sys.path.append('/media/hp/01a64147-0526-48e6-803a-383ca12a7cad/WH/wh/vot/vot-toolkit/native/trax/python');sys.path.append('/media/hp/01a64147-0526-48e6-803a-383ca12a7cad/WH/TRACK/DaSiamRPN/code'); import vot_SiamRPN"
CLIENT: Working directory is /tmp/tpb39fd059_066a_453c_adea_bfa32f51b128
CLIENT: Starting process
CLIENT: Setting up TraX with standard streams connection
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/media/hp/01a64147-0526-48e6-803a-383ca12a7cad/WH/TRACK/DaSiamRPN/code/vot_SiamRPN.py", line 12, in <module>
    import torch
ImportError: No module named torch
CLIENT: Timeout reached. Stopping tracker process ...
CLIENT: Flushing streams
CLIENT: Process should be terminated.
CLIENT: Stopping logger.
CLIENT: Tracker exited (exit code 1)
CLIENT: Unable to establish connection.
CLIENT: Cleaning up.
CLIENT: Stopping logger thread
CLIENT: Stopping watchdog thread
CLIENT: Trying to stop process using protocol.
Tracker execution interrupted: Unable to establish connection.

**Comment by xjtuwh** [comment]
我修改了环境，并用pip安装了torch-0.4.1，同样出错：
Testing TraX protocol support for tracker SiamRPN.
CLIENT: Creating process /usr/bin/python  -c "import sys; sys.path.append('/media/hp/01a64147-0526-48e6-803a-383ca12a7cad/WH/wh/vot/vot-toolkit/native/trax/python');sys.path.append('/media/hp/01a64147-0526-48e6-803a-383ca12a7cad/WH/TRACK/DaSiamRPN/code'); import vot_SiamRPN"
CLIENT: Working directory is /tmp/tpe05ea2e8_806e_4c04_a71d_8b70ac292c6f
CLIENT: Starting process
CLIENT: Setting up TraX with standard streams connection
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/media/hp/01a64147-0526-48e6-803a-383ca12a7cad/WH/TRACK/DaSiamRPN/code/vot_SiamRPN.py", line 12, in <module>
    import torch
  File "/home/hp/.local/lib/python2.7/site-packages/torch/__init__.py", line 80, in <module>
    from torch._C import *
RuntimeError: stoi
请问这是什么原因？

**Comment by lb1100** [comment]
Add one line of code in tracker_SiamRPN.m
```
set_global_variable('python','/path/to/python');
tracker_command = generate_python_command('vot_SiamRPN', {'/PATH/TO/CODE/FOLDER/'});
```
vot-toolkit will use system python by default.

**Comment by foolwood** [comment]
> 我修改了环境，并用pip安装了torch-0.4.1，同样出错：
> Testing TraX protocol support for tracker SiamRPN.
> CLIENT: Creating process /usr/bin/python -c "import sys; sys.path.append('/media/hp/01a64147-0526-48e6-803a-383ca12a7cad/WH/wh/vot/vot-toolkit/native/trax/python');sys.path.append('/media/hp/01a64147-0526-48e6-803a-383ca12a7cad/WH/TRACK/DaSiamRPN/code'); import vot_SiamRPN"
> CLIENT: Working directory is /tmp/tpe05ea2e8_806e_4c04_a71d_8b70ac292c6f
> CLIENT: Starting process
> CLIENT: Setting up TraX with standard streams connection
> Traceback (most recent call last):
> File "", line 1, in 
> File "/media/hp/01a64147-0526-48e6-803a-383ca12a7cad/WH/TRACK/DaSiamRPN/code/vot_SiamRPN.py", line 12, in 
> import torch
> File "/home/hp/.local/lib/python2.7/site-packages/torch/**init**.py", line 80, in 
> from torch._C import *
> RuntimeError: stoi
> 请问这是什么原因？


MATLAB 不支持PyTorch0.4.1！！！


https://github.com/votchallenge/vot-toolkit/issues/173

**Comment by xjtuwh** [comment]
OK，那我能用pytorch 0.4.1以下版本在VOT套件中运行吗？

**Comment by foolwood** [comment]
@xjtuwh 
Thanks for your question. This repository is tested on python2.7 and PyTorch 0.3.1. You should use the same env.

If you still have a question, you can reopen this issue. But for now, I should close it.
