### ISSUE TITLE
To adapt it to local video stream

### ISSUE THREAD

**Issue by guy-guy** [foolwood/DaSiamRPN#31]
Hi Wang,

Can the code be adapted to local video stream? 
Will the pre-trained model released in this repository still be effective?

Thank you.

**Comment by foolwood** [comment]
@guy-guy 
Of course, this code is easy to integrate into any application, we write a [demo](https://github.com/foolwood/DaSiamRPN/blob/master/code/demo.py) (less than 40 lines) to test our tracker.
