### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by dengyang1** [foolwood/DaSiamRPN#34]
target_pos[0] = max(0, min(state['im_w'], target_pos[0]))
    target_pos[1] = max(0, min(state['im_h'], target_pos[1]))
    target_sz[0] = max(10, min(state['im_w'], target_sz[0]))
    target_sz[1] = max(10, min(state['im_h'], target_sz[1]))

我想问下这几句代码具体有啥作用呢？

**Comment by HengLan** [comment]
> 体有啥

Make sure the object are not too small (than 10x10) or too big (than image size). The original SiamFC may get the object size 1x1. Obviously, this is not true. These four lines are smart and useful in tracking in my opinion.

**Comment by dengyang1** [comment]
谢谢回复，代码我理解错了，所以没弄懂这两句的意思
