### ISSUE TITLE
how to generate the labels? 

### ISSUE THREAD

**Issue by zyh0904** [foolwood/DaSiamRPN#37]
groundtruth是在crop训练数据时 一起缩放得到的boundingbox吗？

**Comment by foolwood** [comment]
是的。
labels包含两个部分，一个部分是boundingbox，这个boundingbox是相对于crop来resize的。
另一个是分类，crop的boundingbox和anchor box 的IOU大于0.6的为正样本， IOU小于0.3的为负样本。

请仔细阅读文章，这样的提问是对自己最大的不尊重。

**Comment by foolwood** [comment]
我的微信是wangqiang1ban。
如果有疑问可以直接加微信沟通。issues是为了维护代码bug而存在的。
