### ISSUE TITLE
Question about overall system speed

### ISSUE THREAD

**Issue by jazzseow** [foolwood/DaSiamRPN#7]
May i ask what do you mean by this statement?

"The proposed tracker obtains state-of-the-art accuracy in comprehensive experiments of short-term and long-term visual tracking benchmarks, while the **overall system speed is still far from being real-time**"

**Comment by foolwood** [comment]
The overall system speed is about 150FPS. The general definition of real-time is 25FPS.
So we claim that the overall system speed is still far from being real-time. (150 >> 25)
