### ISSUE TITLE
尺度问题

### ISSUE THREAD

**Issue by DiatYang** [foolwood/DaSiamRPN#8]
给的demo里面好像没有加上图像金子塔，当图片尺度变化较大时就容易跑偏

**Comment by foolwood** [comment]
@DiatYang 
前半句话是对的。后半句话从哪里得到的？
没有使用图像金字塔正是该算法能达到100FPS以上的原因。通过bbox regression，不需要金字塔也可以回归出尺度的变换。

**Comment by DiatYang** [comment]
好的，谢谢回答
