### ISSUE TITLE
about speed reproduction

### ISSUE THREAD

**Issue by lzw19951010** [foolwood/DaSiamRPN#9]
Thanks for your great work! I have tested your code. The good thing is the bbox results is the same as yours, however, I cannot reproduce your claimed 110/160 FPS as your paper described. It would be great if you can share more details with me. Test environment is E5-2643@3.40GHz and TITAN X.

Test details:

![screenshot from 2018-08-28 21-48-03](https://user-images.githubusercontent.com/9997493/44727193-0fedcc80-ab0c-11e8-857d-b9a98fe33d3f.png)

**Comment by lzw19951010** [comment]
I guess so. Again, thank you for your great work!  @foolwood

**Comment by nationalflag** [comment]
Would you share the small SiamRPN model reported in the ECCV2018 paper?
